pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
		git branch: 'main', credentialsId: 'github-token', 
            url:'https://github.com/Gang517/test_jenkins2.git'
            }
        }
    }
}